### ISSUE TITLE
 expected a map, got: nil

### ISSUE THREAD

**Issue by rbroderi** [apognu/unicli#1]
trying to run and get the following error, tried with and without specifying connection settings in json file or on command line.
** (BadMapError) expected a map, got: nil
    (elixir) lib/map.ex:423: Map.get(nil, :host, nil)
    (unicli) lib/unicli.ex:25: anonymous fn/3 in UniCLI.Settings.check/1
    (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
    (unicli) lib/unicli.ex:24: UniCLI.Settings.check/1
    (unicli) lib/unicli.ex:54: UniCLI.main/1
    (elixir) lib/kernel/cli.ex:105: anonymous fn/3 in Kernel.CLI.exec_fun/2
root@unifi:/opt/unicli#  expected a map, got: nil

**Comment by apognu** [comment]
Can you show me your configuration file (redacting sensitive information)?

**Comment by apognu** [comment]
Apparently, there is an issue with the environment variables, I'll look into it.

But as far as I could see, the configuration file works properly.

**Comment by rbroderi** [comment]
Thank you, being able to get information from controller via command line
would be super useful

**Comment by apognu** [comment]
I just pushed an update to master that fixes the use of environment variable to configure a one-time run. The Docker image should be rebuilt in a few minutes on the hub.

Still no clue why you could not configure it via the JSON file, could you paste it here?
